AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Intelligent Document Processing with Amazon Textract

Parameters:
  NotificationEmail:
    Type: String
    Description: Email address for processing notifications
    Default: your-email@example.com

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.11
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: document-processor
        LOG_LEVEL: INFO

Resources:
  # S3 Bucket for document storage
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-documents-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: MoveToGlacierAfter90Days
            Status: Enabled
            Prefix: processed/
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER

  # Lambda permission for S3 to invoke
  DocumentProcessorFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DocumentProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${AWS::StackName}-documents-${AWS::AccountId}'

  # Main processing Lambda function
  DocumentProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-processor'
      CodeUri: src/document_processor/
      Handler: app.lambda_handler
      Description: Process documents using Amazon Textract
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
          SNS_TOPIC_ARN: !Ref ProcessingNotificationTopic
          BUCKET_NAME: !Ref DocumentBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - S3WritePolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - Statement:
            - Effect: Allow
              Action:
                - textract:AnalyzeDocument
                - textract:DetectDocumentText
                - textract:StartDocumentAnalysis
                - textract:GetDocumentAnalysis
              Resource: '*'
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProcessingNotificationTopic.TopicName
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt ProcessingDLQ.Arn

  # DynamoDB table for extracted data
  DocumentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-documents'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: document_id
          AttributeType: S
        - AttributeName: upload_timestamp
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: document_id
          KeyType: HASH
        - AttributeName: upload_timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: upload_timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # SNS Topic for notifications
  ProcessingNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-notifications'
      DisplayName: Document Processing Notifications
      KmsMasterKeyId: alias/aws/sns

  # Email subscription (requires confirmation)
  ProcessingNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref ProcessingNotificationTopic
      Endpoint: !Ref NotificationEmail

  # Dead Letter Queue for failed processing
  ProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-dlq'
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: alias/aws/sqs

  # CloudWatch Log Group
  ProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${DocumentProcessorFunction}'
      RetentionInDays: 30

  # CloudWatch Alarm for errors
  ProcessingErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-processing-errors'
      AlarmDescription: Alert when document processing has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DocumentProcessorFunction
      AlarmActions:
        - !Ref ProcessingNotificationTopic

  # CloudWatch Alarm for DLQ messages
  DLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-dlq-messages'
      AlarmDescription: Alert when messages are sent to DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ProcessingDLQ.QueueName
      AlarmActions:
        - !Ref ProcessingNotificationTopic

Outputs:
  DocumentBucket:
    Description: S3 bucket for document uploads
    Value: !Ref DocumentBucket
    Export:
      Name: !Sub '${AWS::StackName}-bucket'

  DocumentTable:
    Description: DynamoDB table for extracted data
    Value: !Ref DocumentTable
    Export:
      Name: !Sub '${AWS::StackName}-table'

  ProcessorFunction:
    Description: Lambda function ARN
    Value: !GetAtt DocumentProcessorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-function'

  NotificationTopic:
    Description: SNS topic for notifications
    Value: !Ref ProcessingNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-topic'

  UploadCommand:
    Description: Command to upload test documents
    Value: !Sub 'aws s3 cp your-document.pdf s3://${DocumentBucket}/incoming/'

  QueryCommand:
    Description: Command to query processed documents
    Value: !Sub 'aws dynamodb scan --table-name ${DocumentTable} --max-items 5'
